// packages/jsxstyle-solid/src/componentFactory.tsx
import {
  componentStyles,
  DeprecatedJsxstyleComponentName,
  JsxstyleComponentName,
} from '../../jsxstyle-utils/src';
import { styleCache } from './styleCache';
import type { JsxstyleProps, ValidComponentPropValue } from './types';
import { Dynamic, createComponent, mergeProps } from 'solid-js/web';
import type { JSX } from 'solid-js';

type Props<T extends ValidComponentPropValue> = JsxstyleProps<T> & {
  children?: JSX.Element;
};

export function componentFactory(
  displayName: JsxstyleComponentName | DeprecatedJsxstyleComponentName
) {
  const tagName = 'div';
  const defaultProps = componentStyles[displayName];

  const component = <T extends ValidComponentPropValue = 'div'>(
    props: Props<T>
  ): JSX.Element => {
    const extractedProps = styleCache.getComponentProps(
      { ...defaultProps, ...props },
      'class'
    );
    return createComponent(
      Dynamic,
      mergeProps(
        {
          get component() {
            return props.component || tagName;
          },
        },
        extractedProps
      )
    );
  };

  return component;
}

// packages/jsxstyle/react/src/componentFactory.ts
import {
  componentStyles,
  DeprecatedJsxstyleComponentName,
  JsxstyleComponentName,
} from 'jsxstyle/utils/src';
import { styleCache } from './styleCache';
import type { JsxstyleProps, ValidComponentPropValue } from './types';
import * as React from 'react';

export function componentFactory(
  displayName: JsxstyleComponentName | DeprecatedJsxstyleComponentName
) {
  const tagName = 'div';
  const defaultProps = componentStyles[displayName];

  const component = <T extends ValidComponentPropValue = 'div'>(
    props: React.PropsWithChildren<JsxstyleProps<T>>
  ): React.ReactElement => {
    const Component: any = props.component || tagName;
    const extractedProps = styleCache.getComponentProps(props);
    return React.createElement(Component, extractedProps);
  };

  component.displayName = displayName;
  component.defaultProps = defaultProps;

  return component;
}
